/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SurfacePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  resultLimit: 10,
  searchMode: "highlights",
  debounceDelayMs: 1e3,
  searchContentLength: 500,
  readwisePath: "readwise"
};

// src/SurfaceView.ts
var import_obsidian = require("obsidian");
function isSafeUrl(url) {
  try {
    const parsed = new URL(url);
    return parsed.protocol === "https:" || parsed.protocol === "http:";
  } catch (e) {
    return false;
  }
}
var VIEW_TYPE_SURFACE = "surface-view";
var SurfaceView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
    this.lastMarkdownLeaf = null;
    this.onRefresh = null;
    this.onGoDeeper = null;
    this.onBack = null;
    this.onCheckCli = null;
    this.onOpenSettings = null;
    this.contentEl_ = this.contentEl;
  }
  getViewType() {
    return VIEW_TYPE_SURFACE;
  }
  getDisplayText() {
    return "Surface";
  }
  getIcon() {
    return "book-open";
  }
  async onOpen() {
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if (leaf && leaf.view instanceof import_obsidian.MarkdownView) {
          this.lastMarkdownLeaf = leaf;
        }
      })
    );
    const active = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (active) {
      this.lastMarkdownLeaf = active.leaf;
    }
    this.renderNoFile();
  }
  async onClose() {
    this.lastMarkdownLeaf = null;
    this.contentEl_.empty();
  }
  renderSetup() {
    this.contentEl_.empty();
    const el = this.contentEl_.createEl("div", { cls: "surface-setup" });
    el.createEl("h3", { text: "Readwise CLI not found" });
    el.createEl("p", {
      text: "Surface requires the Readwise CLI to search your highlights and documents."
    });
    el.createEl("p", { text: "To install, run:" });
    const code = el.createEl("div", { cls: "surface-setup-code" });
    code.createEl("code", { text: "npm install -g @readwise/cli" });
    code.createEl("br");
    code.createEl("code", { text: "readwise login" });
    const linkP = el.createEl("p");
    const link = linkP.createEl("a", { text: "Readwise CLI docs", cls: "surface-link" });
    const docsUrl = "https://readwise.io/cli";
    link.href = docsUrl;
    link.addEventListener("click", (e) => {
      e.preventDefault();
      window.open(docsUrl);
    });
    const actions = el.createEl("div", { cls: "surface-setup-actions" });
    const checkBtn = actions.createEl("button", { cls: "mod-cta", text: "Check again" });
    checkBtn.addEventListener("click", () => {
      if (this.onCheckCli)
        this.onCheckCli();
    });
    const settingsBtn = actions.createEl("button", { text: "Open settings" });
    settingsBtn.addEventListener("click", () => {
      if (this.onOpenSettings)
        this.onOpenSettings();
    });
  }
  renderNoFile() {
    this.contentEl_.empty();
    this.contentEl_.createEl("div", {
      cls: "surface-status",
      text: "Open a note to see related highlights."
    });
  }
  renderLoading() {
    this.contentEl_.empty();
    this.contentEl_.createEl("div", {
      cls: "surface-status",
      text: "Searching..."
    });
  }
  renderError(message) {
    this.contentEl_.empty();
    const el = this.contentEl_.createEl("div", { cls: "surface-status surface-error" });
    el.createEl("strong", { text: "Error" });
    el.createEl("p", { text: message });
  }
  renderEmpty(searchLabel, hasHistory) {
    this.contentEl_.empty();
    this.addToolbar(0, searchLabel, hasHistory);
    this.contentEl_.createEl("div", {
      cls: "surface-status",
      text: "No related highlights found."
    });
  }
  renderResults(results, searchLabel, hasHistory) {
    this.contentEl_.empty();
    this.addToolbar(results.length, searchLabel, hasHistory);
    const container = this.contentEl_.createEl("div", { cls: "surface-results" });
    for (const result of results) {
      if (result.type === "highlight") {
        this.renderHighlightCard(container, result.data);
      } else {
        this.renderDocumentCard(container, result.data);
      }
    }
  }
  addToolbar(count, searchLabel, hasHistory) {
    const wrapper = this.contentEl_.createEl("div", { cls: "surface-toolbar" });
    const row = wrapper.createEl("div", { cls: "surface-toolbar-row" });
    const buttons = row.createEl("div", { cls: "surface-toolbar-buttons" });
    if (hasHistory) {
      const backBtn = buttons.createEl("button", {
        text: "\u2190 Back"
      });
      backBtn.addEventListener("click", () => {
        if (this.onBack)
          this.onBack();
      });
    }
    const btn = buttons.createEl("button", {
      text: "Refresh"
    });
    btn.addEventListener("click", () => {
      if (this.onRefresh)
        this.onRefresh();
    });
    row.createEl("span", {
      cls: "surface-count",
      text: `${count} result${count !== 1 ? "s" : ""}`
    });
    if (searchLabel) {
      wrapper.createEl("div", {
        cls: "surface-search-label",
        text: searchLabel
      });
    }
  }
  renderHighlightCard(container, h) {
    const card = container.createEl("div", { cls: "surface-card" });
    const header = card.createEl("div", { cls: "surface-card-header" });
    header.createEl("span", { cls: "surface-card-title", text: h.title || "Unknown source" });
    if (h.author) {
      header.createEl("span", { cls: "surface-card-author", text: ` \u2014 ${h.author}` });
    }
    card.createEl("blockquote", { cls: "surface-card-text", text: h.text });
    if (h.note) {
      card.createEl("div", { cls: "surface-card-note", text: h.note });
    }
    if (h.tags && h.tags.length > 0) {
      const tagsEl = card.createEl("div", { cls: "surface-card-tags" });
      for (const tag of h.tags) {
        tagsEl.createEl("span", { cls: "surface-tag", text: `#${tag}` });
      }
    }
    const actions = card.createEl("div", { cls: "surface-card-actions" });
    const insertBtn = actions.createEl("button", {
      cls: "mod-cta",
      text: "Insert"
    });
    insertBtn.addEventListener("click", () => {
      this.insertHighlight(h);
    });
    const deeperBtn = actions.createEl("button", {
      text: "Go Deeper \u2192"
    });
    deeperBtn.addEventListener("click", () => {
      if (this.onGoDeeper)
        this.onGoDeeper(h.text);
    });
    if (h.url && isSafeUrl(h.url)) {
      const link = actions.createEl("a", { cls: "surface-link", text: "Open in Readwise" });
      link.href = h.url;
      link.addEventListener("click", (e) => {
        e.preventDefault();
        window.open(h.url);
      });
    }
  }
  renderDocumentCard(container, d) {
    const card = container.createEl("div", { cls: "surface-card surface-card-document" });
    const header = card.createEl("div", { cls: "surface-card-header" });
    header.createEl("span", { cls: "surface-card-title", text: d.title || "Untitled" });
    if (d.author) {
      header.createEl("span", { cls: "surface-card-author", text: ` \u2014 ${d.author}` });
    }
    if (d.summary) {
      card.createEl("p", { cls: "surface-card-summary", text: d.summary });
    }
    const meta = card.createEl("div", { cls: "surface-card-meta" });
    if (d.category) {
      meta.createEl("span", { cls: "surface-meta-item", text: d.category });
    }
    if (d.site_name) {
      meta.createEl("span", { cls: "surface-meta-item", text: d.site_name });
    }
    const actions = card.createEl("div", { cls: "surface-card-actions" });
    const docUrl = d.source_url || d.url;
    if (docUrl && isSafeUrl(docUrl)) {
      const link = actions.createEl("a", { cls: "surface-link", text: "Open source" });
      link.href = docUrl;
      link.addEventListener("click", (e) => {
        e.preventDefault();
        window.open(docUrl);
      });
    }
  }
  insertHighlight(h) {
    const mdLeaf = this.lastMarkdownLeaf;
    if (!mdLeaf || !(mdLeaf.view instanceof import_obsidian.MarkdownView)) {
      new import_obsidian.Notice("Open a note first to insert a highlight.");
      return;
    }
    const view = mdLeaf.view;
    const editor = view.editor;
    this.app.workspace.setActiveLeaf(mdLeaf, { focus: true });
    editor.focus();
    const escWiki = (s) => s.replace(/\[/g, "\\[").replace(/\]/g, "\\]");
    const source = h.title ? `[[${escWiki(h.title)}]]` : "Unknown source";
    const author = h.author ? ` \u2014 [[${escWiki(h.author)}]]` : "";
    const text = h.text.replace(/\n/g, "\n> ");
    const callout = `> [!quote] ${source}${author}
> ${text}

`;
    editor.replaceSelection(callout);
  }
};

// src/SurfaceSettingTab.ts
var import_obsidian2 = require("obsidian");
var SurfaceSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Readwise CLI path").setDesc(
      "Path to the readwise CLI binary. Leave as 'readwise' to auto-detect."
    ).addText(
      (text) => text.setPlaceholder("readwise").setValue(this.plugin.settings.readwisePath).onChange(async (value) => {
        this.plugin.settings.readwisePath = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Result limit").setDesc("Maximum number of results to show (1-50).").addSlider(
      (slider) => slider.setLimits(1, 50, 1).setValue(this.plugin.settings.resultLimit).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.resultLimit = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Search mode").setDesc("What to search: highlights, documents, or both.").addDropdown(
      (dropdown) => dropdown.addOption("highlights", "Highlights").addOption("documents", "Documents").addOption("both", "Both").setValue(this.plugin.settings.searchMode).onChange(async (value) => {
        this.plugin.settings.searchMode = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Debounce delay (ms)").setDesc("Wait time before searching after switching notes (200-5000).").addSlider(
      (slider) => slider.setLimits(200, 5e3, 100).setValue(this.plugin.settings.debounceDelayMs).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.debounceDelayMs = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Search content length").setDesc("Number of characters from note body to include in search (100-2000).").addSlider(
      (slider) => slider.setLimits(100, 2e3, 100).setValue(this.plugin.settings.searchContentLength).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.searchContentLength = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/readwiseCli.ts
var import_child_process = require("child_process");
var import_fs = require("fs");
var TIMEOUT_MS = 15e3;
var COMMON_BIN_DIRS = [
  "/opt/homebrew/bin",
  "/usr/local/bin",
  "/usr/bin",
  "/bin"
];
var COMMON_PATHS = COMMON_BIN_DIRS.map((d) => `${d}/readwise`);
function isCliInstalled(configured) {
  const resolved = resolveCliPath(configured);
  if (resolved !== "readwise")
    return Promise.resolve(true);
  return new Promise((resolve) => {
    (0, import_child_process.execFile)("which", ["readwise"], { timeout: 3e3 }, (error) => {
      resolve(!error);
    });
  });
}
function resolveCliPath(configured) {
  if (configured && configured !== "readwise") {
    return configured;
  }
  for (const p of COMMON_PATHS) {
    try {
      (0, import_fs.accessSync)(p, import_fs.constants.X_OK);
      return p;
    } catch (e) {
    }
  }
  return configured || "readwise";
}
function parseCliJson(stdout) {
  try {
    return JSON.parse(stdout);
  } catch (e) {
    throw new Error("Readwise CLI returned invalid JSON. Check that the CLI is authenticated and working.");
  }
}
function run(cliPath, args) {
  return new Promise((resolve, reject) => {
    const env = {
      ...process.env,
      PATH: COMMON_BIN_DIRS.join(":") + ":" + (process.env.PATH || "")
    };
    (0, import_child_process.execFile)(
      cliPath,
      args,
      { timeout: TIMEOUT_MS, maxBuffer: 10 * 1024 * 1024, env },
      (error, stdout, stderr) => {
        if (error) {
          const msg = (stderr == null ? void 0 : stderr.trim()) || error.message;
          reject(new Error(`readwise CLI error: ${msg}`));
        } else {
          resolve(stdout);
        }
      }
    );
  });
}
async function searchHighlights(term, limit, cliPath) {
  var _a;
  const resolved = resolveCliPath(cliPath);
  const stdout = await run(resolved, [
    "readwise-search-highlights",
    "--vector-search-term",
    term,
    "--limit",
    String(limit),
    "--json"
  ]);
  const parsed = parseCliJson(stdout);
  const raw = Array.isArray(parsed) ? parsed : (_a = parsed.results) != null ? _a : [];
  return raw.map((r) => {
    var _a2;
    return {
      id: r.id,
      text: r.attributes.highlight_plaintext,
      title: r.attributes.document_title,
      author: r.attributes.document_author,
      url: r.url,
      note: r.attributes.highlight_note,
      category: r.attributes.document_category,
      tags: (_a2 = r.attributes.highlight_tags) != null ? _a2 : [],
      score: r.score
    };
  });
}
async function searchDocuments(query, limit, cliPath) {
  const resolved = resolveCliPath(cliPath);
  const stdout = await run(resolved, [
    "reader-search-documents",
    "--vector-search-term",
    query,
    "--limit",
    String(limit),
    "--json"
  ]);
  const parsed = parseCliJson(stdout);
  if (Array.isArray(parsed)) {
    return parsed;
  }
  if (parsed && typeof parsed === "object" && Array.isArray(parsed.results)) {
    return parsed.results;
  }
  return [];
}

// src/main.ts
var MAX_HISTORY = 20;
var SurfacePlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.generation = 0;
    this.cliAvailable = true;
    this.currentFilePath = null;
    this.historyStack = [];
    this.currentResults = [];
    this.debounceTimer = null;
  }
  async onload() {
    await this.loadSettings();
    this.cliAvailable = await isCliInstalled(this.settings.readwisePath);
    if (!this.cliAvailable) {
      new import_obsidian3.Notice("Surface: Readwise CLI not found. Open the Surface sidebar for setup instructions.");
    }
    this.registerView(VIEW_TYPE_SURFACE, (leaf) => new SurfaceView(leaf));
    this.addRibbonIcon("book-open", "Open Surface sidebar", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-surface-sidebar",
      name: "Open Surface sidebar",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "search-readwise-selection",
      name: "Search Readwise for selection",
      editorCallback: async (editor) => {
        const sel = editor.getSelection();
        if (sel.trim()) {
          await this.activateView(true);
          this.executeSearch(sel.trim(), "Selection search");
        }
      }
    });
    this.addSettingTab(new SurfaceSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        const sel = editor.getSelection().trim();
        if (sel) {
          menu.addItem((item) => {
            item.setTitle("Search Readwise for selection").setIcon("book-open").onClick(async () => {
              await this.activateView(true);
              this.executeSearch(sel, "Selection search");
            });
          });
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        var _a;
        if (!this.isSurfaceViewVisible())
          return;
        const file = this.app.workspace.getActiveFile();
        const path = (_a = file == null ? void 0 : file.path) != null ? _a : null;
        if (path && path !== this.currentFilePath) {
          this.currentFilePath = path;
          this.debouncedTriggerSearch();
        }
      })
    );
  }
  onunload() {
    if (this.debounceTimer)
      clearTimeout(this.debounceTimer);
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_SURFACE);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView(skipSearch = false) {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_SURFACE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: VIEW_TYPE_SURFACE,
          active: true
        });
      }
    }
    if (leaf) {
      await workspace.revealLeaf(leaf);
    }
    if (!skipSearch) {
      this.triggerSearch();
    }
  }
  debouncedTriggerSearch() {
    if (this.debounceTimer)
      clearTimeout(this.debounceTimer);
    this.debounceTimer = setTimeout(() => {
      this.debounceTimer = null;
      this.triggerSearch();
    }, this.settings.debounceDelayMs);
  }
  async triggerSearch() {
    this.historyStack = [];
    this.currentResults = [];
    this.currentLabel = void 0;
    if (!this.isSurfaceViewVisible())
      return;
    const view = this.getView();
    if (!view)
      return;
    if (!this.cliAvailable) {
      view.renderSetup();
      return;
    }
    const file = this.app.workspace.getActiveFile();
    if (!file || !(file instanceof import_obsidian3.TFile) || file.extension !== "md") {
      view.renderNoFile();
      return;
    }
    const searchTerm = await this.buildSearchTerm(file);
    if (!searchTerm) {
      view.renderNoFile();
      return;
    }
    await this.executeSearch(searchTerm);
  }
  async executeSearch(term, searchLabel) {
    const view = this.getView();
    if (!view)
      return;
    const gen = ++this.generation;
    view.renderLoading();
    try {
      const results = [];
      const { searchMode, resultLimit, readwisePath } = this.settings;
      if (searchMode === "highlights" || searchMode === "both") {
        const highlights = await searchHighlights(term, resultLimit, readwisePath);
        for (const h of highlights) {
          results.push({ type: "highlight", data: h });
        }
      }
      if (searchMode === "documents" || searchMode === "both") {
        const docs = await searchDocuments(term, resultLimit, readwisePath);
        for (const d of docs) {
          results.push({ type: "document", data: d });
        }
      }
      if (gen !== this.generation)
        return;
      this.currentResults = results;
      this.currentLabel = searchLabel;
      const hasHistory = this.historyStack.length > 0;
      if (results.length === 0) {
        view.renderEmpty(searchLabel, hasHistory);
      } else {
        view.renderResults(results, searchLabel, hasHistory);
      }
    } catch (err) {
      if (gen !== this.generation)
        return;
      const message = err instanceof Error ? err.message : String(err);
      if (message.includes("ENOENT") || message.includes("EACCES")) {
        this.cliAvailable = false;
        view.renderSetup();
      } else {
        view.renderError(message);
      }
    }
  }
  goDeeper(highlightText) {
    if (this.historyStack.length >= MAX_HISTORY) {
      this.historyStack.shift();
    }
    this.historyStack.push({
      results: this.currentResults,
      searchLabel: this.currentLabel
    });
    const truncated = highlightText.length > 60 ? highlightText.slice(0, 57) + "..." : highlightText;
    this.executeSearch(highlightText, `Deeper: ${truncated}`);
  }
  goBack() {
    const entry = this.historyStack.pop();
    if (!entry)
      return;
    const view = this.getView();
    if (!view)
      return;
    this.currentResults = entry.results;
    this.currentLabel = entry.searchLabel;
    const hasHistory = this.historyStack.length > 0;
    if (entry.results.length === 0) {
      view.renderEmpty(entry.searchLabel, hasHistory);
    } else {
      view.renderResults(entry.results, entry.searchLabel, hasHistory);
    }
  }
  async buildSearchTerm(file) {
    const content = await this.app.vault.cachedRead(file);
    const cache = this.app.metadataCache.getFileCache(file);
    const parts = [];
    parts.push(file.basename);
    if (cache == null ? void 0 : cache.frontmatter) {
      const fm = cache.frontmatter;
      const props = ["tags", "topics", "categories", "keywords", "subject"];
      for (const prop of props) {
        const val = fm[prop];
        if (!val)
          continue;
        if (Array.isArray(val)) {
          parts.push(val.join(" "));
        } else if (typeof val === "string") {
          parts.push(val);
        }
      }
    }
    let body = content;
    if (cache == null ? void 0 : cache.frontmatterPosition) {
      body = content.slice(cache.frontmatterPosition.end.offset + 1);
    }
    if ((cache == null ? void 0 : cache.headings) && cache.headings.length > 0) {
      parts.push(cache.headings.map((h) => h.heading).join(" "));
    }
    const lines = body.split("\n");
    let paragraph = "";
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#"))
        continue;
      paragraph = trimmed;
      break;
    }
    if (paragraph) {
      parts.push(paragraph.slice(0, this.settings.searchContentLength));
    }
    return parts.join(" ").trim();
  }
  getView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_SURFACE);
    if (leaves.length > 0) {
      const view = leaves[0].view;
      if (!view.onRefresh) {
        view.onRefresh = () => this.triggerSearch();
      }
      if (!view.onGoDeeper) {
        view.onGoDeeper = (text) => this.goDeeper(text);
      }
      if (!view.onBack) {
        view.onBack = () => this.goBack();
      }
      if (!view.onCheckCli) {
        view.onCheckCli = async () => {
          this.cliAvailable = await isCliInstalled(this.settings.readwisePath);
          if (this.cliAvailable) {
            this.triggerSearch();
          } else {
            new import_obsidian3.Notice("Readwise CLI still not found.");
          }
        };
      }
      if (!view.onOpenSettings) {
        view.onOpenSettings = () => {
          try {
            this.app.setting.open();
            this.app.setting.openTabById(this.manifest.id);
          } catch (e) {
            new import_obsidian3.Notice("Could not open settings. Open them manually from Settings \u2192 Surface.");
          }
        };
      }
      return view;
    }
    return null;
  }
  /**
   * Returns true if the Surface panel exists and is currently visible
   * (not deferred/hidden because the user switched to another tab).
   */
  isSurfaceViewVisible() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_SURFACE);
    if (leaves.length === 0)
      return false;
    const leaf = leaves[0];
    return leaf.isDeferred !== true;
  }
};
